static final int TEXT_WIDGET=1; 
final int SCREEN_X = 1280;
final int SCREEN_Y = 720;
final int EVENT_BUTTON1=1;                               //event of clicking button1
final int EVENT_BUTTON2=2;                                // event of clicking forward // event of hovering
final int EVENT_BUTTON3= 3;                               // event of clicking home in list
final int EVENT_BUTTON4= 4;                               // event of clicking home in classification
final int EVENT_BUTTON5= 5;                               // event of clicking home
final int EVENT_BUTTON6= 6;                               // event of clicking #covid
final int EVENT_BUTTON7= 7;                               // event of clicking #covid 19
final int EVENT_BUTTON8= 8;                               // event of clicking #Covid19ireland
final int EVENT_BUTTON9= 9;                               // event of clicking #Covid19USA
final int EVENT_BUTTON10= 10;                             // event of clicking #COVIDSecondWave
final int EVENT_BUTTON11= 11;                             // event of clicking #COVID19SWEEDEN/Sverige
final int EVENT_BUTTON12= 12;                             // event of clicking state by state 
final int EVENT_BUTTON13= 13;                             // event of clicking state by Texas
final int EVENT_BUTTON14= 14;                             // event of clicking state by Arizona
final int EVENT_BUTTON15= 15;                             // event of clicking state back from state
final int EVENT_BUTTON16= 16;                             // event of clicking state by Cali
final int EVENT_BUTTON17= 17;                             // event of clicking state by Nev
final int EVENT_BUTTON18= 18;                             // event of clicking state by Utah
final int EVENT_BUTTON19= 19;                             // event of clicking state by Oregan
final int EVENT_BUTTON20= 20;                             // event of clicking state by Washington
final int EVENT_BUTTON21= 21;                             // event of clicking state by florida
final int EVENT_BUTTON22= 22;                             // event of clicking state by kansas
final int EVENT_BUTTON23= 23;                             // event of clicking state by georgia
final int EVENT_BUTTON24= 24;                             // event of clicking state by OK
final int EVENT_BUTTON25= 25;                             // event of clicking state by HW
final int EVENT_BUTTON26= 26;                             // event of clicking state by INDiana
final int EVENT_BUTTON27= 27;                             // event of clicking state by Ohio
final int EVENT_BUTTON28= 28;                             // event of clicking state by TEN
final int EVENT_BUTTON29= 29;                             // event of clicking state by Vermont
final int EVENT_BUTTON30= 30;                             // event of clicking state by Wisconsin 
final int EVENT_BUTTON31= 31;                             // event of clicking state by illonios 
final int EVENT_BUTTON32= 32;                             // event of clicking state by mass 
final int EVENT_BUTTON33= 33;                             // event of clicking state by Nebraska
final int EVENT_BUTTON34= 34;                             // event of clicking state by North Car
final int EVENT_BUTTON35= 35;                             // event of clicking state by Soth Car
final int EVENT_BUTTON36= 36;                             // event of clicking state by idaho
final int EVENT_BUTTON37= 37;                             // event of clicking state by  montana
final int EVENT_BUTTON38= 38;                             // event of clicking state by wyoming
final int EVENT_BUTTON39= 39;                             // event of clicking state by colardo
final int EVENT_BUTTON40= 40;                             // event of clicking state by new mexico
final int EVENT_BUTTON41= 41;                             // event of clicking state by north dakota
final int EVENT_BUTTON42= 42;                             // event of clicking state by south dakota
final int EVENT_BUTTON43= 43;                             // event of clicking state by minnnisota
final int EVENT_BUTTON44= 44;                             // event of clicking state by ipwa
final int EVENT_BUTTON45= 45;                             // event of clicking state by missiori
final int EVENT_BUTTON46= 46;                             // event of clicking state by arkinsas
final int EVENT_BUTTON47= 47;                             // event of clicking state by lousinana
final int EVENT_BUTTON48= 48;                             // event of clicking state by michigan
final int EVENT_BUTTON49= 49;                             // event of clicking state by kentucky
final int EVENT_BUTTON50= 50;                             // event of clicking state by missipi
final int EVENT_BUTTON51= 51;                             // event of clicking state by alabama
final int EVENT_BUTTON52= 52;                             // event of clicking state by maine
final int EVENT_BUTTON53= 53;                             // event of clicking state by new hamp
final int EVENT_BUTTON54= 54;                             // event of clicking state by R.Island
final int EVENT_BUTTON55= 55;                             // event of clicking state by conneticut
final int EVENT_BUTTON56= 56;                             // event of clicking state by delaware
final int EVENT_BUTTON57= 57;                             // event of clicking state by maryland
final int EVENT_BUTTON58= 58;                             // event of clicking state by west virgina
final int EVENT_BUTTON59= 59;                             // event of clicking state by virginia
final int EVENT_BUTTON60= 60;                             // event of clicking state by new york
final int EVENT_BUTTON61= 61;                             // event of clicking state by penn
final int EVENT_BUTTON62= 62;                             // event of clicking state by alaska
final int EVENT_BUTTON63=63;                              // event of clicking weekly cases 
final int EVENT_BUTTON64=64;                              // event of clicking Texas covid guidlines @ coded by Kevin and Aritro in 30 minute intervals
final int EVENT_BUTTON65=65;                              // event of clicking Arizona covid guidlines
final int EVENT_BUTTON66=66;                              // event of clicking California covid guidlines
final int EVENT_BUTTON67=67;                              // event of clicking Nevada covid guidlines
final int EVENT_BUTTON68=68;                              // event of clicking Utah covid guidlines
final int EVENT_BUTTON69=69;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON70=70;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON71=71;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON72=72;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON73=73;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON74=74;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON75=75;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON76=76;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON77=77;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON78=78;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON79=79;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON80=80;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON81=81;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON82=82;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON83=83;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON84=84;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON85=85;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON86=86;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON87=87;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON88=88;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON89=89;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON90=90;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON91=91;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON92=92;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON93=93;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON94=94;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON95=95;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON96=96;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON97=97;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON98=98;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON99=99;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON100=100;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON101=101;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON102=102;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON103=103;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON104=104;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON105=105;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON106=106;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON107=107;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON108=108;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON109=109;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON110=110;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON111=111;                              // event of clicking Oregon covid guidlines
final int EVENT_BUTTON112=112;                              // event of clicking Oregon covid guidlines
final int EVENT_NULL=0;                                   // none of the above
final int EVENT_BACKWARD = 4;
final int PADDING = 10;
final int firstMAP = 70;
final int secondMAP = -50;
final int xAxis = 962;
final int yAxis = 800;
final int xTry = 700;
final int yTry = 100;
final int zTry = 30;
final int colourFour = 520809;
final int noOfStates = 54;
final int xLength = 120;
final int yWidth = 200;
final int noOfWeeks = 8;
final int noOfPoisitions = 54;
